[workspace]
resolver = "2"
members = ["days/*"]

[workspace.dependencies]
adventurous = { git = "https://github.com/maxdeviant/adventurous.git", rev = "2c1906caab825ba6dad835b8ffc151d03816d727" }
anyhow = "1.0"
enum-map = "2.7.3"
indoc = "2.0.4"
nom = "7.1.3"
pretty_assertions = "1.4.0"
