instruments template day:
    cargo instruments --profile instruments --template "{{template}}" --bin {{day}}

profile-heap day:
    cargo run --profile dhat --package {{day}} --features dhat-heap

bench day:
    cargo bench --quiet {{day}}

bench-all:
    cargo bench --quiet > benchmarks.txt

flamegraph day:
    cargo flamegraph --profile flamegraph --root --package {{day}} --output days/{{day}}/flamegraph.svg

init day:
    cargo generate --path ./template --name {{day}} --force --destination $(realpath ./days)
